version: '3.1'
services:
  mariadb:
    container_name: mariadb_container
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./mariadb/conf.d:/etc/mysql/conf.d"
      - "./mariadb/data:/var/lib/mysql"
    environment:
      MARIADB_DATABASE: test
      MARIADB_USER: tester
      MARIADB_PASSWORD: t1234
      MARIADB_ROOT_PASSWORD: "1234"

  springboot-app:
    container_name: backend_container
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/test
      SPRING_DATASOURCE_USERNAME: "tester"
      SPRING_DATASOURCE_PASSWORD: "t1234"
    depends_on:
      - mariadb
    volumes:
      - ./src/main/resources/application.yml:/app/config/application.yml
    command: [ "java", "-jar", "app.jar", "--spring.config.location=file:/app/config/application.yml" ]

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
