version: '3.1'
services:
  springboot-app:
    container_name: backend_container
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
  db:
    container_name: mariadb_container
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
